# Goal
uint8 action_id
---
# Result
bool action_result
---

## ExecArmAction.action
#@brief An interface for executing arm actions
#@param action_id The id of the action to execute
#                1 : Move to home position
#                2 : Move to ready position (down to pick up/place object)
#                3 : Put object to stock
#                4 : Get object from stock
#                5 : Grab
#                6 : Release
#@param action_result True if the action was successful, False otherwise
