teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 1
    scale_linear:
      x: 0.2
      y: 0.2
    scale_linear_turbo:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.9

    require_enable_button : false  
    enable_turbo_button: -1  